version: "3.9"

services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    container_name: app_supervision_mib_backend
    volumes:
      - ./backend/token.txt:/app/token.txt
    ports:
      - "5001:5001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  gateway:
    build:
      context: ./api-gateway
    container_name: app_supervision_mib_gateway
    ports:
      - "5000:5000"
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
    container_name: app_supervision_mib_frontend
    ports:
      - "5002:5002"
    depends_on:
      - gateway
