name: CI   # lint + build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # ────────────────────────── LINT ──────────────────────────
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: |
            api-gateway/Dockerfile
            backend/Dockerfile
            frontend/Dockerfile

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install ruff
        run: pip install ruff==0.4.*

      - name: Run ruff
        run: ruff .

  # ────────────────────────── BUILD ─────────────────────────
  build-images:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build gateway image
        uses: docker/build-push-action@v5
        with:
          context: ./api-gateway
          tags: mib-gateway:ci
          push: false

      - name: Build backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          tags: mib-backend:ci
          push: false

      - name: Build frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          tags: mib-frontend:ci
          push: false

